version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: always
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    networks:
      - appnet

  proxy:
    build:
      context: ./nginx-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
