version: "3.8"

services:
  # El Reverse Proxy es el único que expone puertos al exterior
  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80" # Puerto HTTP estándar
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - appnet

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod # Usaremos un Dockerfile optimizado para prod
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod # Usaremos un Dockerfile optimizado para prod
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
