name: CI

on:
  push:
  pull_request:

jobs:
  build_and_test:
    name: Build, Lint & Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # SonarCloud necesita el historial completo para un análisis preciso de nuevos issues
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          # Habilitar caché para npm acelera las instalaciones en ejecuciones futuras
          cache: 'npm'

      - name: Install all dependencies
        run: npm install

      - name: Run linting for all projects
        run: npm run lint

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          # Escanea todos los proyectos (frontend y backend) definidos en los workspaces
          args: --all-projects --severity-threshold=high

      - name: SonarCloud Scan (backend)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Requerido por la acción de SonarCloud
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: backend

      - name: SonarCloud Scan (frontend)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
